cd build/addons/sourcemod/scripting
./compile.sh ams_redux.sp
./compile.sh antisolorage.sp
./compile.sh bossmode.sp
./compile.sh deadrun_helper.sp
./compile.sh ff2_admin_menu.sp
./compile.sh ff2_admin_menu_fork.sp
./compile.sh ff2_boss_prefs.sp
./compile.sh ff2_boss_selection.sp
./compile.sh ff2_boss_toggle.sp
./compile.sh ff2_bossname.sp
./compile.sh ff2_custom_attribute_adapter.sp
./compile.sh ff2_kstreak_pref.sp
./compile.sh ff2_mana_system.sp
./compile.sh ff2_MP.sp
./compile.sh ff2stats.sp
./compile.sh hudminmode.sp
./compile.sh menurage_platform.sp
./compile.sh respawn_tickets.sp
./compile.sh rps4points.sp
./compile.sh streaker.sp
./compile.sh toxicspots.sp
./compile.sh tts.sp
./compile.sh vshbots_logic.sp
./compile.sh vshbots_move.sp

cd freaks
./compile.sh *.sp